networks:
  cart_network:
    driver: bridge

services:
  postgres:
    image: 'postgres:17-bullseye'
    container_name: cart_db
    networks:
      cart_network:
        aliases:
          - psql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRESS_DB=cart
    command: postgres -N 1000
   
  kafka:
    image: 'bitnami/kafka:3.9.0'
    container_name: cart_kafka
    hostname: localhost
    networks:
      - cart_network
    ports:
      - 9092:9092
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
